<?php

namespace ContainerIb5G89v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EWVVWRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eWVVW_R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eWVVW_R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'or' => ['privates', 'App\\Repository\\OfferRepository', 'getOfferRepositoryService', true],
        ], [
            'or' => 'App\\Repository\\OfferRepository',
        ]);
    }
}
