<?php

namespace ContainerIb5G89v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WqRSYGCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WqRSYGC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WqRSYGC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CandidateController::delete' => ['privates', '.service_locator.tnUlgwd', 'get_ServiceLocator_TnUlgwdService', true],
            'App\\Controller\\CandidateController::edit' => ['privates', '.service_locator.tnUlgwd', 'get_ServiceLocator_TnUlgwdService', true],
            'App\\Controller\\CandidateController::index' => ['privates', '.service_locator.4TTtHel', 'get_ServiceLocator_4TTtHelService', true],
            'App\\Controller\\CandidateController::show' => ['privates', '.service_locator.tnUlgwd', 'get_ServiceLocator_TnUlgwdService', true],
            'App\\Controller\\FrontController::offerDetails' => ['privates', '.service_locator.eWVVW_R', 'get_ServiceLocator_EWVVWRService', true],
            'App\\Controller\\FrontController::offers' => ['privates', '.service_locator.eWVVW_R', 'get_ServiceLocator_EWVVWRService', true],
            'App\\Controller\\FrontController::offersDep' => ['privates', '.service_locator.eWVVW_R', 'get_ServiceLocator_EWVVWRService', true],
            'App\\Controller\\FrontController::offersPerJob' => ['privates', '.service_locator.eWVVW_R', 'get_ServiceLocator_EWVVWRService', true],
            'App\\Controller\\JobController::delete' => ['privates', '.service_locator.wv06f8x', 'get_ServiceLocator_Wv06f8xService', true],
            'App\\Controller\\JobController::edit' => ['privates', '.service_locator.wv06f8x', 'get_ServiceLocator_Wv06f8xService', true],
            'App\\Controller\\JobController::index' => ['privates', '.service_locator._r0oHHG', 'get_ServiceLocator_R0oHHGService', true],
            'App\\Controller\\JobController::show' => ['privates', '.service_locator.wv06f8x', 'get_ServiceLocator_Wv06f8xService', true],
            'App\\Controller\\OfferController::delete' => ['privates', '.service_locator.7IsKrbY', 'get_ServiceLocator_7IsKrbYService', true],
            'App\\Controller\\OfferController::edit' => ['privates', '.service_locator.7IsKrbY', 'get_ServiceLocator_7IsKrbYService', true],
            'App\\Controller\\OfferController::index' => ['privates', '.service_locator.RRBnNCt', 'get_ServiceLocator_RRBnNCtService', true],
            'App\\Controller\\OfferController::show' => ['privates', '.service_locator.7IsKrbY', 'get_ServiceLocator_7IsKrbYService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CandidateController:delete' => ['privates', '.service_locator.tnUlgwd', 'get_ServiceLocator_TnUlgwdService', true],
            'App\\Controller\\CandidateController:edit' => ['privates', '.service_locator.tnUlgwd', 'get_ServiceLocator_TnUlgwdService', true],
            'App\\Controller\\CandidateController:index' => ['privates', '.service_locator.4TTtHel', 'get_ServiceLocator_4TTtHelService', true],
            'App\\Controller\\CandidateController:show' => ['privates', '.service_locator.tnUlgwd', 'get_ServiceLocator_TnUlgwdService', true],
            'App\\Controller\\FrontController:offerDetails' => ['privates', '.service_locator.eWVVW_R', 'get_ServiceLocator_EWVVWRService', true],
            'App\\Controller\\FrontController:offers' => ['privates', '.service_locator.eWVVW_R', 'get_ServiceLocator_EWVVWRService', true],
            'App\\Controller\\FrontController:offersDep' => ['privates', '.service_locator.eWVVW_R', 'get_ServiceLocator_EWVVWRService', true],
            'App\\Controller\\FrontController:offersPerJob' => ['privates', '.service_locator.eWVVW_R', 'get_ServiceLocator_EWVVWRService', true],
            'App\\Controller\\JobController:delete' => ['privates', '.service_locator.wv06f8x', 'get_ServiceLocator_Wv06f8xService', true],
            'App\\Controller\\JobController:edit' => ['privates', '.service_locator.wv06f8x', 'get_ServiceLocator_Wv06f8xService', true],
            'App\\Controller\\JobController:index' => ['privates', '.service_locator._r0oHHG', 'get_ServiceLocator_R0oHHGService', true],
            'App\\Controller\\JobController:show' => ['privates', '.service_locator.wv06f8x', 'get_ServiceLocator_Wv06f8xService', true],
            'App\\Controller\\OfferController:delete' => ['privates', '.service_locator.7IsKrbY', 'get_ServiceLocator_7IsKrbYService', true],
            'App\\Controller\\OfferController:edit' => ['privates', '.service_locator.7IsKrbY', 'get_ServiceLocator_7IsKrbYService', true],
            'App\\Controller\\OfferController:index' => ['privates', '.service_locator.RRBnNCt', 'get_ServiceLocator_RRBnNCtService', true],
            'App\\Controller\\OfferController:show' => ['privates', '.service_locator.7IsKrbY', 'get_ServiceLocator_7IsKrbYService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CandidateController::delete' => '?',
            'App\\Controller\\CandidateController::edit' => '?',
            'App\\Controller\\CandidateController::index' => '?',
            'App\\Controller\\CandidateController::show' => '?',
            'App\\Controller\\FrontController::offerDetails' => '?',
            'App\\Controller\\FrontController::offers' => '?',
            'App\\Controller\\FrontController::offersDep' => '?',
            'App\\Controller\\FrontController::offersPerJob' => '?',
            'App\\Controller\\JobController::delete' => '?',
            'App\\Controller\\JobController::edit' => '?',
            'App\\Controller\\JobController::index' => '?',
            'App\\Controller\\JobController::show' => '?',
            'App\\Controller\\OfferController::delete' => '?',
            'App\\Controller\\OfferController::edit' => '?',
            'App\\Controller\\OfferController::index' => '?',
            'App\\Controller\\OfferController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CandidateController:delete' => '?',
            'App\\Controller\\CandidateController:edit' => '?',
            'App\\Controller\\CandidateController:index' => '?',
            'App\\Controller\\CandidateController:show' => '?',
            'App\\Controller\\FrontController:offerDetails' => '?',
            'App\\Controller\\FrontController:offers' => '?',
            'App\\Controller\\FrontController:offersDep' => '?',
            'App\\Controller\\FrontController:offersPerJob' => '?',
            'App\\Controller\\JobController:delete' => '?',
            'App\\Controller\\JobController:edit' => '?',
            'App\\Controller\\JobController:index' => '?',
            'App\\Controller\\JobController:show' => '?',
            'App\\Controller\\OfferController:delete' => '?',
            'App\\Controller\\OfferController:edit' => '?',
            'App\\Controller\\OfferController:index' => '?',
            'App\\Controller\\OfferController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
