<?php

namespace ContainerIb5G89v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportOffersCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportOffersCommand' shared autowired service.
     *
     * @return \App\Command\ImportOffersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ImportOffersCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'PoleEmploiService.php';

        $a = ($container->privates['App\\Repository\\OfferRepository'] ?? $container->load('getOfferRepositoryService'));

        $container->privates['App\\Command\\ImportOffersCommand'] = $instance = new \App\Command\ImportOffersCommand(new \App\Services\PoleEmploiService(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), $a, 'http://rh.ptitlabo.xyz/'), $a, ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('offer:import');

        return $instance;
    }
}
